# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  paths:
      - '**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./
          output_dir: artifact
          # Default is true, can set to false to only get PDF files
          build_html: false
      - name: UploadArtifact
        uses: actions/upload-artifact@master
        with:
          name: build-${{ github.run_number }}
          path: artifact
